# ServerProperties类
server:
  port: 8080
  servlet:
    context-path: /community
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#把thymeleaf默认的缓存关闭
# ThymeleafProperties类
spring:
  thymeleaf:
    cache: false